package org.onedigit.study.project.euler;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * @author ahmed
 *
 */
public class EvenFibonacci
{
    private static int MAX = 4_000_000;
    // private static int MAX = 90;
    
    public static void evenSum()
    {
        int a = 1;
        int b = 2;
        int next = 0;
        int evenSum = 0;
        while (next < MAX) {
            next = a + b;
            a = b;
            b = next;
            if ((a & 0x1) == 0) { // a is even
                // System.out.println("b is even: " + a);
                evenSum += a;
            }
        }
        System.out.println("evenSum = " + evenSum);
    }
    
    public static void main(String[] args)
    {
        evenSum();
    }
}
